name: Runner
run-name: Runner ${{ github.run_number }}

on:
  schedule:
    - cron: "15,45 * * * *"

  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    container: ghcr.io/opencidn/cidn/runner:v0.0.108
    steps:
      - shell: sh
        run: runner --handler-name=cidn-${{ github.run_number }} --update-duration=10s --duration=5h --concurrency=2 ${{ secrets.ARGS_CIDN }}
