name: Runner
run-name: Runner ${{ github.run_id }}

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    container: ghcr.io/opencidn/cidn/runner:v0.0.42
    steps:
      - shell: sh
        run: runner --handler-name=${{ github.run_id }} --update-duration=10s ${{ secrets.ARGS }}
